### ISSUE TITLE
Test HDFS

### ISSUE THREAD

**Issue by RonVander** [RonVander/SEBC#11]

**Comment by mfernest** [comment]
Please note in the command you used below:
```
time hadoop jar /opt/cloudera/parcels/CDH-5.13.2-1.cdh5.13.2.p0.3/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar teragen -Dmapreduce.map.memory.mb=768 -Dmapreduce.reduce.memory.mb=768 -Dmapred.reduce.tasks=16 -Dmapred.map.tasks=16 -Ddfs.blocksize=64000000 65536 /user/hilary/tgen
```
You asked for a total of 65,536 records (instead of 65,536,000). The following steps in the exercise are could be seen as checks against this output: if you calculate the number of blocks or the size of the files inspected, you have a way of knowing if the job ran according to plan (or that you submitted the right job).

This submission suffers from a critical error for that reason. I reviewed the instructions for this stage and believe they are clear and unambiguous. Unfortunately, this means I must mark this stage as incomplete.
